source 'https://rubygems.org'

gem 'rake'
gem 'directory_watcher', '=1.4.1'
gem 'jekyll',            '=1.0.3'
gem 'liquid',            '=2.5.1'
gem 'redcarpet',         '=3.0.0'
gem 'maruku',            '=0.6.1'
gem 'rdiscount',         '=1.6.8'
gem 'RedCloth',          '=4.2.9'
gem 'kramdown',          '=1.0.2'
